version: '3.8'

services:
  app:
    image: hamna2004/inventory-app:latest
    build: .
    ports:
      - "3000:3000"
    environment:
      - PG_USER=ITS-Bazaar_owner
      - PG_HOST=ep-icy-night-a5w7jcxg-pooler.us-east-2.aws.neon.tech
      - PG_NAME=ITS-Bazaar
      - PG_PASSWORD=npg_67sZPVhYBFaN
      - PG_PORT=5432
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=hamnapassword123
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  rabbitmq_data: