apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
      - name: inventory-app
        image: hamna2004/inventory-tracking:latest
        ports:
        - containerPort: 3000
        env:
        - name: PG_USER
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: PG_USER
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: PG_HOST
        - name: PG_NAME
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: PG_NAME
        - name: PG_PORT
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: PG_PORT
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: PG_PASSWORD
        - name: BASIC_AUTH_USERNAME
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: BASIC_AUTH_USERNAME
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: BASIC_AUTH_PASSWORD
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq:5672"
        - name: REDIS_URL
          value: "redis://redis:6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m" 