apiVersion: v1
kind: Secret
metadata:
  name: inventory-secrets
type: Opaque
stringData:
  PG_USER: "ITS-Bazaar_owner"
  PG_PASSWORD: "npg_67sZPVhYBFaN"
  BASIC_AUTH_PASSWORD: "hamnapassword123"
  RABBITMQ_DEFAULT_PASS: "guest" 